name: {{name}}_sidekick
description: Sidekick CLI for {{name}}
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  main:

dependencies:
  csv: ^5.0.0
  intl: ^0.17.0
  sidekick_core: ^0.5.0
  timeago: ^3.0.2

dev_dependencies:
  lint: ^1.5.3
