name: {{name}}_sidekick
description: Sidekick CLI for {{name}}
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  main:

dependencies:
  sidekick_core: '>=0.9.0 <1.0.0'

dev_dependencies:
  lint: ^1.5.3
