name: {{name}}_sidekick
description: Sidekick CLI for {{name}}
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  {{name}}: {{name}}

dependencies:
  csv: ^5.0.0
  intl: ^0.17.0
  sidekick_core: ^0.3.3
  timeago: ^3.0.2


dev_dependencies:
  lint: ^1.5.3
