name: sidekick_test
description: Shared utilities for testing sidekick packages.
version: 2.0.0
publish_to: none

environment:
  sdk: '>=3.6.0 <3.999.0'

dependencies:
  args: ^2.1.0
  dartx: ^1.0.0
  dcli: ^8.2.0
  mocktail: ^1.0.0
  path: ^1.8.1
  pubspec_manager: ^3.0.0
  test: '>1.25.0 <2.0.0'

dev_dependencies:
  lint: ^2.0.0
