name: sidekick_vault
description: Reads project secrets stored encrypted on the local filesystem
version: 0.5.4
repository: https://github.com/phntmxyz/sidekick

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  actions_toolkit_dart: ^0.5.0
  dcli: # provided by sidekick_core
  sidekick_core: '>=0.7.0 <1.0.0'

dev_dependencies:
  lint: ^1.5.0
  test: ^1.20.0
  sidekick_plugin_installer: ^0.1.0