name: sidekick_vault
description: Reads project secrets stored encrypted on the local filesystem
version: 1.2.0
repository: https://github.com/phntmxyz/sidekick/tree/main/sidekick_vault
issue_tracker: https://github.com/phntmxyz/sidekick/labels/sidekick_vault
topics:
  - sidekick
  - cli
  - sidekick-plugin

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  actions_toolkit_dart: ^0.5.0
  dcli: ^4.0.1-beta.4
  sidekick_core: ^3.0.0-preview.1

dev_dependencies:
  dcli_core: ^4.0.0
  lint: '>=1.5.0 <3.0.0'
  prompts: ^2.0.0
  sidekick_plugin_installer: ^1.2.0
  test: ^1.20.0
