name: sk_sidekick
description: Sidekick CLI for sk
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

executables:
  main:

dependencies:
  dcli: ^2.2.2
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.0
  sidekick_core:
    path: ../sidekick_core
  yaml: ^3.1.1

dev_dependencies:
  lint: ^2.0.0
  sidekick_test:
    path: ../sidekick_test
  test: ^1.20.0

sidekick:
  cli_version: 2.0.6
