name: sk_sidekick
description: Sidekick CLI for sk
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.10.7 <4.0.0"

executables:
  main:

dependencies:
  dcli: ^8.2.0
  pub_semver: ^2.1.1
  pubspec_manager: ^3.0.0
  pubspec_parse: ^1.2.0
  sidekick_core: ^3.1.0
  yaml: ^3.1.1

dev_dependencies:
  lint: ^2.0.0
  sidekick_test:
    git:
      url: https://github.com/phntmxyz/sidekick.git
      ref: sidekick_core-v3.1.0
      path: sidekick_test
  test: ^1.20.0

sidekick:
  cli_version: 3.1.0
