name: sidekick_plugin_installer
description: Helpers for plugin installers to easily install themselves into a sidekick cli
version: 0.3.1
repository: https://github.com/phntmxyz/sidekick/tree/main/sidekick_plugin_installer
issue_tracker: https://github.com/phntmxyz/sidekick/labels/sidekick_plugin_installer
topics:
  - sidekick
  - cli

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: '>=4.0.0 <6.0.0'
  dcli: ^1.15.0
  sidekick_core: ^1.0.0

dev_dependencies:
  lint: ^1.0.0
  pubspec: ^2.3.0
  # Include again when updated to Dart 3
  #sidekick_test:
  #  path: ../sidekick_test
  sidekick_test:
    git:
      url: https://github.com/phntmxyz/sidekick.git
      ref: sidekick_core-v1.2.0
      path: sidekick_test
  test: '>1.21.0 <2.0.0'
