name: sidekick_plugin_installer
description: Helpers for plugin installers to easily install themselves into a sidekick cli
version: 1.0.0
repository: https://github.com/phntmxyz/sidekick/tree/main/sidekick_plugin_installer
issue_tracker: https://github.com/phntmxyz/sidekick/labels/sidekick_plugin_installer
topics:
  - sidekick
  - cli

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: '>=4.0.0 <6.0.0'
  dcli: ^2.2.0
  sidekick_core: ^2.0.0

dev_dependencies:
  lint: ^2.0.0
  pubspec: ^2.3.0
  sidekick_test:
    path: ../sidekick_test
  test: '>1.21.0 <2.0.0'
