name: sidekick
description: Creates a CLI for your flutter app for custom tasks and automation
version: 2.0.2
repository: https://github.com/phntmxyz/sidekick/tree/main/sidekick
issue_tracker: https://github.com/phntmxyz/sidekick/labels/sidekick
topics:
  - sidekick
  - cli

environment:
  sdk: '>=2.19.0 <3.999.0'

dependencies:
  acronym: ^0.5.1
  args: ^2.3.2
  cli_completion: ^0.3.0
  dartx: ^1.0.0
  dcli: '>=2.2.0 <=2.2.3'
  http: '>=0.13.3 <=2.0.0'
  meta: ^1.5.0
  path: ^1.8.0
  process: ^4.2.4
  recase: ^4.0.0
  sidekick_core: ^2.1.0

dev_dependencies:
  lint: ^2.0.0
  sidekick_test:
    path: ../sidekick_test
  test: ^1.21.6
  test_process: ^2.0.3

executables:
  sidekick:
