name: sidekick
description: Creates a CLI for your flutter app for custom tasks and automation
version: 3.1.0
repository: https://github.com/phntmxyz/sidekick/tree/main/sidekick
issue_tracker: https://github.com/phntmxyz/sidekick/labels/sidekick
topics:
  - sidekick
  - cli

environment:
  sdk: '>=3.6.0 <3.999.0'

dependencies:
  # direct dependencies
  acronym: '>=0.5.1 <=0.5.1'
  args: '>=2.3.2 <=2.7.0'
  cli_completion: '>=0.5.0 <=0.5.1'
  dartx: '>=1.0.0 <=1.2.0'
  dcli: '>=8.2.0 <=8.3.0'
  http: '>=0.13.3 <=1.6.0'
  meta: '>=1.5.0 <=1.17.0'
  path: '>=1.8.0 <=1.9.1'
  process: '>=5.0.2 <=5.0.5'
  recase: '>=4.0.0 <=4.1.0'
  sidekick_core: '>=3.1.0 <=3.1.1'

  # transitive dependencies
  _fe_analyzer_shared: '>=93.0.0 <=93.0.0'
  analyzer: '>=10.0.0 <=10.0.0'
  archive: '>=4.0.0 <=4.0.7'
  async: '>=2.0.0 <=2.13.0'
  boolean_selector: '>=2.0.0 <=2.1.2'
  characters: '>=1.0.0 <=1.4.1'
  checked_yaml: '>=2.0.0 <=2.0.4'
  chunked_stream: '>=1.0.0 <=1.4.2'
  circular_buffer: '>=0.12.0 <=0.12.0'
  cli_config: '>=0.2.0 <=0.2.0'
  clock: '>=1.0.0 <=1.1.2'
  collection: '>=1.0.0 <=1.19.1'
  convert: '>=3.0.0 <=3.1.2'
  coverage: '>=1.0.0 <=1.15.0'
  crypto: '>=3.0.0 <=3.0.7'
  csv: '>=6.0.0 <=6.0.0'
  dart_console: '>=4.0.0 <=4.1.2'
  dcli_common: '>=8.0.0 <=8.3.0'
  dcli_terminal: '>=8.0.0 <=8.3.0'
  equatable: '>=2.0.0 <=2.0.8'
  ffi: '>=2.0.0 <=2.1.5'
  file: '>=7.0.0 <=7.0.1'
  fixnum: '>=1.0.0 <=1.1.1'
  frontend_server_client: '>=4.0.0 <=4.0.0'
  functional_data: '>=1.0.0 <=1.2.0'
  glob: '>=2.0.0 <=2.1.3'
  globbing: '>=1.0.0 <=1.0.0'
  http_multi_server: '>=3.0.0 <=3.2.2'
  http_parser: '>=4.0.0 <=4.1.2'
  ini: '>=2.0.0 <=2.1.0'
  intl: '>=0.20.0 <=0.20.2'
  io: '>=1.0.0 <=1.0.5'
  json2yaml: '>=3.0.0 <=3.0.1'
  json_annotation: '>=4.0.0 <=4.9.0'
  logging: '>=1.0.0 <=1.3.0'
  mason_logger: '>=0.3.0 <=0.3.3'
  matcher: '>=0.12.0 <=0.12.18'
  mime: '>=2.0.0 <=2.0.0'
  mocktail: '>=1.0.0 <=1.0.4'
  native_synchronization_temp: '>=0.8.0 <=0.8.0'
  node_preamble: '>=2.0.0 <=2.0.2'
  package_config: '>=2.0.0 <=2.2.0'
  platform: '>=3.0.0 <=3.1.6'
  pool: '>=1.0.0 <=1.5.2'
  posix: '>=6.0.0 <=6.0.3'
  pub_semver: '>=2.0.0 <=2.2.0'
  pubspec_lock: '>=3.0.0 <=3.0.2'
  pubspec_manager: '>=3.0.0 <=3.2.0'
  pubspec_parse: '>=1.0.0 <=1.5.0'
  scope: '>=5.0.0 <=5.1.0'
  settings_yaml: '>=8.0.0 <=8.3.1'
  shelf: '>=1.0.0 <=1.4.2'
  shelf_packages_handler: '>=3.0.0 <=3.0.2'
  shelf_static: '>=1.0.0 <=1.1.3'
  shelf_web_socket: '>=3.0.0 <=3.0.0'
  simple_sparse_list: '>=0.1.0 <=0.1.4'
  source_map_stack_trace: '>=2.0.0 <=2.1.2'
  source_maps: '>=0.10.0 <=0.10.13'
  source_span: '>=1.0.0 <=1.10.1'
  stack_trace: '>=1.0.0 <=1.12.1'
  stream_channel: '>=2.0.0 <=2.1.4'
  string_scanner: '>=1.0.0 <=1.4.1'
  strings: '>=4.0.0 <=4.0.1'
  sum_types: '>=0.3.0 <=0.3.5'
  system_info2: '>=4.0.0 <=4.1.0'
  term_glyph: '>=1.0.0 <=1.2.2'
  test_api: '>=0.7.0 <=0.7.9'
  test_core: '>=0.6.0 <=0.6.15'
  time: '>=2.0.0 <=2.1.6'
  typed_data: '>=1.0.0 <=1.4.0'
  unicode: '>=1.0.0 <=1.1.8'
  uuid: '>=4.0.0 <=4.5.2'
  validators2: '>=5.0.0 <=5.1.0'
  vm_service: '>=15.0.0 <=15.0.2'
  watcher: '>=1.0.0 <=1.2.1'
  web: '>=1.0.0 <=1.1.1'
  web_socket: '>=1.0.0 <=1.0.1'
  web_socket_channel: '>=3.0.0 <=3.0.3'
  webkit_inspection_protocol: '>=1.0.0 <=1.2.1'
  win32: '>=5.0.0 <=5.15.0'
  yaml: '>=3.0.0 <=3.1.3'
  yaml_edit: '>=2.0.0 <=2.2.3'

dev_dependencies:
  dcli_core: ^8.2.0
  lint: ^2.0.0
  sidekick_test:
    path: ../sidekick_test
  test: '>1.25.0 <2.0.0'
  test_process: ^2.0.3

executables:
  sidekick:
