name: sidekick_core
description: Shared sidekick commands, plugin engine, migrations, templates and utilities for sidekick CLIs
version: 1.1.0
repository: https://github.com/phntmxyz/sidekick/tree/main/sidekick_core
issue_tracker: https://github.com/phntmxyz/sidekick/labels/sidekick_core

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.1.0
  dartx: ^1.1.0
  dcli: ^1.15.0
  glob: ^2.0.2
  http: ^0.13.5
  meta: ^1.5.0
  # transitive from dcli
  pub_semver: ^2.1.1
  recase: ^4.1.0
  yaml: ^3.1.0
  yaml_edit: ^2.0.3

dev_dependencies:
  fake_http_client: ^1.0.0
  lint: ^1.5.0
  sidekick_test:
    path: ../sidekick_test
  test: ^1.20.0
