name: sidekick_core
description: Reusable code pieces for sidekick CLIs. Provides a project and useful helper methods when working with files
version: 0.5.1
repository: https://github.com/phntmxyz/sidekick

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.1.0
  dartx: '>=0.7.1 <2.0.0'
  dcli: ^1.15.0
  yaml: ^3.1.0

dev_dependencies:
  lint: ^1.5.0
  test: ^1.20.0