name: sidekick_core
description: Shared sidekick commands, plugin engine, migrations, templates and utilities for sidekick CLIs
version: 3.1.1
repository: https://github.com/phntmxyz/sidekick/tree/main/sidekick_core
issue_tracker: https://github.com/phntmxyz/sidekick/labels/sidekick_core
topics:
  - sidekick
  - cli

environment:
  sdk: '>=3.6.0 <3.999.0'

dependencies:
  args: ^2.1.0
  cli_completion: ^0.5.0
  dartx: ^1.1.0
  dcli: ^8.2.0
  glob: ^2.0.2
  http: '>=0.13.5 <2.0.0'
  meta: ^1.5.0
  path: ^1.8.1
  # transitive from dcli
  pub_semver: ^2.1.1
  pubspec_manager: ^3.0.0
  pubspec_parse: ^1.2.0
  recase: ^4.1.0
  win32: ^5.7.0
  yaml: ^3.1.0
  yaml_edit: ^2.0.3

dev_dependencies:
  fake_http_client: ^2.0.0
  lint: ^2.0.0
  sidekick_test:
    path: ../sidekick_test
  test: '>1.25.0 <2.0.0'
