name: sidekick_core
description: Shared sidekick commands, plugin engine, migrations, templates and utilities for sidekick CLIs
version: 2.0.3
repository: https://github.com/phntmxyz/sidekick/tree/main/sidekick_core
issue_tracker: https://github.com/phntmxyz/sidekick/labels/sidekick_core
topics:
  - sidekick
  - cli

environment:
  sdk: '>=2.19.0 <3.999.0'

dependencies:
  args: ^2.1.0
  dartx: ^1.1.0
  dcli: '>=2.2.0 <=2.2.3'
  glob: ^2.0.2
  http: ^0.13.5
  meta: ^1.5.0
  path: ^1.8.1
  # transitive from dcli
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.0
  recase: ^4.1.0
  yaml: ^3.1.0
  yaml_edit: ^2.0.3

dependency_overrides:
  # `pubspec2` is a transitive dependency of `dcli`, but `pubspec2` v2.5.0 breaks `dcli` v2.2.3
  pubspec2: '>=2.0.0 <2.5.0'

dev_dependencies:
  fake_http_client: ^1.0.0
  lint: ^2.0.0
  sidekick_test:
    path: ../sidekick_test
  test: ^1.20.0
